(imports)

In [1]:
%matplotlib inline
import numpy as np

# Part 1
### 1.1 Initialize 2 Arrays

In [2]:
y_hat = np.asarray([-0.5,-0.45,-0.40,-0.35,-0.30,-0.25,-0.20,-0.15,-0.10,-0.05,0.10,0.15,0.20,0.25,0.30,0.35,0.40,0.45,0.50,0.55])
y_hat

array([-0.5 , -0.45, -0.4 , -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 ,
       -0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55])

In [3]:
y = np.asarray([0.2,0.225,0.25,0.275,0.3,0.325,0.35,0.375,0.4,0.425,0.45,0.475,0.5,0.525,0.55,0.575,0.6,0.625,0.65,0.675])
y

array([0.2  , 0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ,
       0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625,
       0.65 , 0.675])

### 1.2 Shape & Dimensions

In [4]:
y_hat.shape


(20,)

In [5]:
y.shape

(20,)

In [6]:
y_hat.ndim

1

In [7]:
y.ndim

1

### 1.3 Mean Squared Error (MSE)

In [8]:
def MSE(yhat,y):
    if yhat.shape[0]!=y.shape[0]:
        return "Error: Arrays not the same length."
    return (1/yhat.shape[0])*(np.sum((yhat-y)**2))
L = MSE(y_hat,y)
L

0.20593750000000002

### 1.4 Mean Absolute Error (MAE)

In [9]:
def MAE(yhat,y):
    if yhat.shape[0]!=y.shape[0]:
        return "Error: Arrays not the same length."
    return (1/yhat.shape[0])*(np.sum(np.absolute(yhat-y)))
L = MAE(y_hat,y)
L

0.41250000000000003

### 1.5 Mean Squared Logarithmic Error

In [10]:
def MSLE(yhat,y):
    if yhat.shape[0]!=y.shape[0]:
        return "Error: Arrays not the same length."
    return (1/yhat.shape[0])*(np.sum((np.log(yhat+1)-np.log(y+1))**2))
L = MSLE(y_hat,y)
L

0.21501724837153394

### 1.6 Mean Absolute Percentage Error

In [11]:
def MAPE(yhat,y):
    if yhat.shape[0]!=y.shape[0]:
        return "Error: Arrays not the same length."
    return (1/yhat.shape[0])*(np.sum(np.absolute((yhat-y)/y)))
L = MAPE(y_hat,y)
L

1.2470984525886264

# Part 2
### 1.1 Initialize 1D Array

In [12]:
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 1.2 Reshape Array into 2D

In [13]:
N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 1.3 2nd Row

In [14]:
R2 = N[1,]
R2

array([5, 6, 7, 8])

### 1.4 Minimum values in each column

In [15]:
Min = np.min(N, axis=0)
Min

array([1, 2, 3, 4])

### 1.5 Location of minimum values in each column
    (locateElement supports 1D and 2D Arrays)

In [16]:
def locateElement(element,array):
    xnum = array.shape[0]
    if array.ndim==1:
        for x in range(xnum):
            if array[x]==element:
                return str(element) + ' is located in index ' + str(x)
    elif  array.ndim==2:
        ynum = array.shape[1]
        for x in range(xnum):
            for y in range(ynum):
                if array[x,y]==element:
                    return str(element) + ' is located in index ' + str(x) + ',' + str(y)

for x in Min:
    print(locateElement(x,N))

1 is located in index 0,0
2 is located in index 0,1
3 is located in index 0,2
4 is located in index 0,3


### 1.6 Average of the Matrix

In [17]:
Avg = np.mean(N)
Avg

8.5

### 1.7 New Vector

In [18]:
V = np.ones((4,), dtype=int)
V

array([1, 1, 1, 1])

### 1.8 Dot Product

In [19]:
Dprod = np.dot(N,V)
Dprod

array([10, 26, 42, 58])